export interface Activity {
  slug: string;
  title: string;
  category: "watersport" | "rafting" | "nusa-penida" | "labuan-bajo";
  description: string;
  longDescription: string;
  price: string;
  duration: string;
  ageRange: string;
  minAge: number;
  maxAge: number;
  image: string;
  gallery: string[];
  badge?: string;
  openHour: string;
  closeHour: string;
  checkInNote: string;
  healthRestrictions: string[];
  dos: string[];
  donts: string[];
  includes: string[];
  excludes: string[];
  insuranceInfo: string;
}

export const watersportActivities: Activity[] = [
  {
    slug: "banana-boat",
    title: "Banana Boat",
    category: "watersport",
    description: "Hold tight and enjoy the thrilling ride on a giant inflatable banana boat pulled by a speedboat across the beautiful Bali sea.",
    longDescription: "One of the most popular watersport activities in Bali! Hop on our giant inflatable banana boat with your friends or family and get pulled by a powerful speedboat across the crystal-clear waters of Tanjung Benoa. Expect lots of splashing, laughing, and unforgettable memories.",
    price: "Rp50K",
    duration: "15 minutes",
    ageRange: "8–65",
    minAge: 8,
    maxAge: 65,
    image: "/activities/banana-boat.webp",
    gallery: [],
    badge: "Most Popular",
    openHour: "08:00",
    closeHour: "17:00",
    checkInNote: "Please arrive 15 minutes before your session.",
    healthRestrictions: ["Heart disease", "Hypertension", "Pregnancy", "Serious congenital illnesses"],
    dos: ["Wear the provided life jacket at all times", "Listen to the instructor's briefing", "Hold the handles firmly", "Have fun!"],
    donts: ["Do not stand on the banana boat", "Do not remove life jacket during activity", "Do not participate if feeling unwell"],
    includes: ["Life jacket", "Safety briefing", "Certified instructor"],
    excludes: ["Personal travel insurance", "Towel", "Sunscreen"],
    insuranceInfo: "All participants are covered by our partner's activity insurance during the session. Coverage includes accidental injury during the activity.",
  },
  {
    slug: "donut-boat",
    title: "Donut Boat",
    category: "watersport",
    description: "Spin and splash on the famous donut-shaped tube pulled by a speedboat — perfect for thrill seekers of all ages.",
    longDescription: "Sit inside a giant inflatable donut ring and hold on as our speedboat whips you around the waves! The circular design creates wild spins and exciting splashes that will leave you screaming with joy.",
    price: "Rp50K",
    duration: "15 minutes",
    ageRange: "8–65",
    minAge: 8,
    maxAge: 65,
    image: "/activities/donut-boat.webp",
    gallery: [],
    openHour: "08:00",
    closeHour: "17:00",
    checkInNote: "Please arrive 15 minutes before your session.",
    healthRestrictions: ["Heart disease", "Hypertension", "Pregnancy", "Serious congenital illnesses"],
    dos: ["Wear life jacket at all times", "Hold handles firmly", "Follow instructor's instructions"],
    donts: ["Do not release handles during activity", "Do not bring valuables"],
    includes: ["Life jacket", "Safety briefing", "Certified instructor"],
    excludes: ["Personal travel insurance", "Towel"],
    insuranceInfo: "Covered by activity insurance during session.",
  },
  {
    slug: "jet-ski",
    title: "Jet Ski",
    category: "watersport",
    description: "Race across the waves on a high-powered jet ski. Feel the speed and freedom of the open Bali sea.",
    longDescription: "Take the wheel of a powerful jet ski and zoom across the shimmering waters of Bali. Whether you're a first-timer or experienced rider, our instructors will guide you for a safe and exhilarating experience.",
    price: "Rp150K",
    duration: "15 minutes",
    ageRange: "8–65",
    minAge: 8,
    maxAge: 65,
    image: "/activities/jet-ski.webp",
    gallery: [],
    badge: "Adrenaline Rush",
    openHour: "08:00",
    closeHour: "17:00",
    checkInNote: "Valid ID required. Arrive 20 minutes early.",
    healthRestrictions: ["Heart disease", "Hypertension", "Pregnancy", "Back/neck injuries"],
    dos: ["Wear life jacket and helmet", "Follow speed limits in designated zones", "Keep safe distance from other watercraft"],
    donts: ["Do not perform stunts", "Do not exceed designated area", "Do not operate under influence"],
    includes: ["Life jacket", "Helmet", "Safety briefing", "Instructor escort"],
    excludes: ["Personal travel insurance"],
    insuranceInfo: "Covered by activity insurance during session.",
  },
  {
    slug: "parasailing",
    title: "Parasailing",
    category: "watersport",
    description: "Soar high above the Bali coastline and enjoy breathtaking aerial views while being towed by a speedboat.",
    longDescription: "Experience the ultimate freedom as you glide through the sky 50 meters above the sea! Parasailing in Bali offers stunning panoramic views of the coastline, ocean, and tropical landscape. Perfect for thrill-seekers and photographers alike.",
    price: "Rp150K",
    duration: "15 minutes",
    ageRange: "8–65",
    minAge: 8,
    maxAge: 65,
    image: "/activities/parasailing.webp",
    gallery: ["/activities/parasailing.webp", "/activities/parasailing-2.webp"],
    badge: "Bird's Eye View",
    openHour: "08:00",
    closeHour: "16:30",
    checkInNote: "Arrive 20 minutes early. Activity subject to weather conditions.",
    healthRestrictions: ["Heart disease", "Hypertension", "Pregnancy", "Fear of heights (not recommended)", "Recent surgeries"],
    dos: ["Wear the provided harness correctly", "Follow all instructor commands", "Relax and enjoy the view"],
    donts: ["Do not unbuckle harness", "Do not panic — stay calm", "Do not bring loose items"],
    includes: ["Harness", "Life jacket", "Safety briefing", "Photo opportunity"],
    excludes: ["Professional photography", "Personal travel insurance"],
    insuranceInfo: "Covered by activity insurance. Weather-related cancellations are rescheduled.",
  },
  {
    slug: "disco-boat",
    title: "Disco Boat",
    category: "watersport",
    description: "Dance on the water! A fun inflatable disco ride that spins, bounces, and plays music for an epic group experience.",
    longDescription: "Get the party started on the water with the Disco Boat! This wild inflatable platform spins and bounces while music plays, creating a unique dance-party-meets-watersport experience. Great for groups and families.",
    price: "Rp75K",
    duration: "15 minutes",
    ageRange: "8–65",
    minAge: 8,
    maxAge: 65,
    image: "/activities/disco-boat.webp",
    gallery: [],
    openHour: "08:00",
    closeHour: "17:00",
    checkInNote: "Please arrive 15 minutes before your session.",
    healthRestrictions: ["Heart disease", "Hypertension", "Pregnancy"],
    dos: ["Hold the handles tightly", "Wear life jacket", "Enjoy the music!"],
    donts: ["Do not bring electronics on the boat", "Do not stand during activity"],
    includes: ["Life jacket", "Safety briefing"],
    excludes: ["Personal travel insurance"],
    insuranceInfo: "Covered by activity insurance during session.",
  },
  {
    slug: "fly-fish",
    title: "Fly Fish",
    category: "watersport",
    description: "Get airborne on a flying fish tube towed by a speedboat — a unique experience that literally lifts you out of the water.",
    longDescription: "The Fly Fish is a specially designed inflatable tube shaped like a fish that can be tilted to make riders fly above the water surface. Hold on tight as you become a human flying fish across the Bali sea!",
    price: "Rp100K",
    duration: "15 minutes",
    ageRange: "8–65",
    minAge: 8,
    maxAge: 65,
    image: "/activities/fly-fish.webp",
    gallery: [],
    openHour: "08:00",
    closeHour: "17:00",
    checkInNote: "Please arrive 15 minutes before your session.",
    healthRestrictions: ["Heart disease", "Hypertension", "Pregnancy", "Back injuries"],
    dos: ["Hold handles firmly", "Wear life jacket", "Keep body flat"],
    donts: ["Do not let go during flight", "Do not bring valuables"],
    includes: ["Life jacket", "Safety briefing", "Certified instructor"],
    excludes: ["Personal travel insurance"],
    insuranceInfo: "Covered by activity insurance during session.",
  },
  {
    slug: "fly-board",
    title: "Fly Board",
    category: "watersport",
    description: "Master the Flyboard — shoot up to 10 meters above the water powered by hydro jets. The ultimate water adventure.",
    longDescription: "Flyboarding is the most thrilling watersport in Bali! Powered by high-pressure water jets attached to a jet ski, you'll be propelled up to 10 meters into the air. With practice, you can perform spins, dives, and acrobatics over the water. Our certified instructors will get you flying in minutes!",
    price: "Rp350K",
    duration: "20 minutes",
    ageRange: "8–65",
    minAge: 8,
    maxAge: 65,
    image: "/activities/fly-board.webp",
    gallery: [],
    badge: "Premium",
    openHour: "08:00",
    closeHour: "16:00",
    checkInNote: "Arrive 30 minutes early. Includes 10-min training session.",
    healthRestrictions: ["Heart disease", "Hypertension", "Pregnancy", "Knee/ankle injuries"],
    dos: ["Attend full training session", "Start slow — learn balance first", "Listen to instructor at all times"],
    donts: ["Do not attempt advanced moves without instructor approval", "Do not wear loose clothing"],
    includes: ["Helmet", "Life jacket", "Wetsuit", "Training session", "Certified instructor"],
    excludes: ["Personal travel insurance", "GoPro footage (available at extra cost)"],
    insuranceInfo: "Full activity insurance provided. Covers accidents during session.",
  },
  {
    slug: "sea-walker",
    title: "Sea Walker",
    category: "watersport",
    description: "Walk on the ocean floor wearing a special helmet and breathe normally — no diving experience needed!",
    longDescription: "Sea Walker (also called Helmet Diving) lets you literally walk on the seabed at 3–5 meters depth while wearing a specially designed helmet that supplies fresh air. No swimming or diving experience required. You'll be surrounded by tropical fish, coral reefs, and the magical underwater world of Bali.",
    price: "Rp350K",
    duration: "30 minutes",
    ageRange: "9–60",
    minAge: 9,
    maxAge: 60,
    image: "/activities/sea-walker.webp",
    gallery: ["/activities/sea-walker.webp", "/activities/sea-walker-2.webp", "/activities/sea-walker-3.webp"],
    badge: "No Experience Needed",
    openHour: "08:00",
    closeHour: "15:30",
    checkInNote: "Arrive 30 minutes early. Medical form required.",
    healthRestrictions: ["Heart disease", "Hypertension", "Pregnancy", "Ear infections", "Claustrophobia", "Recent ear/eye surgeries"],
    dos: ["Fill medical form honestly", "Equalize ear pressure as instructed", "Relax and breathe normally", "Follow dive guide at all times"],
    donts: ["Do not touch corals or marine life", "Do not remove helmet underwater", "Do not go beyond designated depth"],
    includes: ["Helmet", "Wetsuit", "Underwater guide", "Underwater photos"],
    excludes: ["Personal travel insurance", "Video footage (available at extra cost)"],
    insuranceInfo: "Full activity and dive insurance provided. Strict safety protocols in place.",
  },
];

export const raftingPackages = [
  {
    slug: "ayung-river-rafting",
    title: "Ayung River Rafting",
    description: "Navigate the famous Ayung River through lush jungle, waterfalls, and traditional Balinese rice terraces.",
    price: "Rp350K",
    duration: "2 hours on water",
    level: "Beginner–Intermediate",
    distance: "9 km",
    image: "/activities/rafting.webp",
    itinerary: ["Pick-up from hotel (optional)", "Equipment fitting & safety briefing", "2-hour rafting on Ayung River", "Shower & changing facilities", "Buffet lunch at riverside restaurant", "Hotel transfer (optional)"],
    includes: ["Rafting equipment", "Life jacket", "Helmet", "Certified guide", "Insurance", "Buffet lunch", "Shower facilities"],
    excludes: ["Hotel pick-up/drop-off (extra cost)", "Personal items", "Tips"],
  },
  {
    slug: "telaga-waja-rafting",
    title: "Telaga Waja River Rafting",
    description: "For thrill-seekers! The Telaga Waja offers Grade III–IV rapids through spectacular East Bali scenery.",
    price: "Rp400K",
    duration: "2.5 hours on water",
    level: "Intermediate–Advanced",
    distance: "13 km",
    image: "https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=800&q=80",
    itinerary: ["Hotel pick-up", "Equipment & safety briefing", "2.5-hour rafting on Telaga Waja", "Shower & changing facilities", "Indonesian lunch", "Hotel drop-off"],
    includes: ["Full rafting gear", "Certified guide", "Insurance", "Lunch", "Shower"],
    excludes: ["Personal travel insurance upgrade", "Tips"],
  },
];

export const nusaPenidaPackages = [
  {
    slug: "nusa-penida-west-tour",
    title: "Nusa Penida West Tour",
    description: "Visit the iconic Kelingking Beach, Angel's Billabong, Broken Beach, and Crystal Bay in one epic day.",
    price: "Rp450K",
    duration: "Full day (8 hrs)",
    image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80",
    destinations: ["Kelingking Beach (T-Rex Bay)", "Angel's Billabong", "Broken Beach", "Crystal Bay"],
    includes: ["Fast boat transfer", "Private car + driver", "English-speaking guide", "Entrance fees", "Lunch"],
    excludes: ["Hotel pick-up from outside Kuta/Seminyak", "Snorkeling gear", "Personal travel insurance"],
  },
  {
    slug: "nusa-penida-east-tour",
    title: "Nusa Penida East Tour",
    description: "Explore the stunning East coast: Atuh Beach, Teletubbies Hill, Diamond Beach, and Thousand Island viewpoint.",
    price: "Rp450K",
    duration: "Full day (8 hrs)",
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
    destinations: ["Atuh Beach", "Teletubbies Hill", "Diamond Beach", "Thousand Island Viewpoint"],
    includes: ["Fast boat transfer", "Private car + driver", "Guide", "Entrance fees", "Lunch"],
    excludes: ["Hotel transfer outside Bali central areas", "Personal insurance"],
  },
  {
    slug: "nusa-penida-snorkeling",
    title: "Nusa Penida Snorkeling Tour",
    description: "Snorkel with Manta Rays at Manta Point and discover vibrant coral reefs around Nusa Penida.",
    price: "Rp500K",
    duration: "Full day",
    image: "https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=800&q=80",
    destinations: ["Manta Point", "Gamat Bay", "Crystal Bay"],
    includes: ["Fast boat", "Snorkeling equipment", "Guide", "Lunch", "Insurance"],
    excludes: ["Underwater camera", "Extra tips"],
  },
];

export const labuanBajoPackages = [
  {
    slug: "labuan-bajo-2d1n",
    title: "Labuan Bajo 2D1N Island Hopping",
    description: "A quick getaway to the stunning Komodo National Park — see Komodo Dragons, Pink Beach, and pristine waters.",
    price: "Rp1,500K",
    duration: "2 Days / 1 Night",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    highlights: ["Komodo Dragon trekking", "Pink Beach", "Padar Island viewpoint", "Snorkeling at Manta Point"],
    includes: ["Return flight Bali–Labuan Bajo (optional)", "Boat tour", "Accommodation (1 night)", "Guide", "Meals (full board)", "National Park fee"],
    excludes: ["Personal travel insurance", "Alcoholic beverages", "Tips"],
  },
  {
    slug: "labuan-bajo-3d2n",
    title: "Labuan Bajo 3D2N Premium Tour",
    description: "The ultimate Komodo experience — liveaboard or hotel-based with comprehensive island exploration.",
    price: "Rp2,500K",
    duration: "3 Days / 2 Nights",
    image: "https://images.unsplash.com/photo-1501426026826-31c667bdf23d?w=800&q=80",
    highlights: ["Komodo & Rinca trekking", "Pink Beach", "Kanawa Island snorkeling", "Sunset at Padar Island", "Gili Lawa viewpoint"],
    includes: ["Flights (optional)", "Liveaboard / hotel", "All meals", "Guide", "Snorkeling gear", "National Park fees"],
    excludes: ["Personal travel insurance", "Flights (if not selected)", "Alcoholic beverages"],
  },
];
